# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B compile assembly:single --file pom.xml
    - uses: actions/upload-artifact@v2
      with:
        name: target
        path: target/
    - run: mv target/kdecole-notification-bot-0.0.1-SNAPSHOT-jar-with-dependencies.jar kdecole-bot
    - uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "kdecole-bot"
        target: "/usr/bin"
        overwrite: true
